environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - set CI=true
  - npm config set progress=false
  - npm i npm@latest -g
  - node --version
  - npm --version
  - npm install
build: off
version: '{build}'
test_script:
  - npm test
after_test:
  - npx codecov
